### PR TITLE
fix: redirect slashed coins to gov

### LINKED ISSUE #772: Slashed coins should not be burned
Currently, slashed coins are burned.
This behavior should be changed.

Instead of burning slashed funds, they must be redirected to the Governance module account, consistent with how we handle rewards that are withheld from miners during penalties.

Expected behavior:

- [ ] Slashed coins must not be burned.
- [ ] Slashed coins must be transferred to the Governance module account.
- [ ] Implementation should reuse or mirror the existing logic that handles redistribution of miner rewards that are not paid out due to penalties

### PR DESCRIPTION
**Pull request by x0152**
closes #772

### CODE REVIEW

File: inference-chain/x/inference/keeper/collateral_integration_test.go [hunk 1]
```diff
@@ -123,6 +123,7 @@ func setupRealKeepers(t testing.TB) (sdk.Context, keeper.Keeper, collateralKeepe
 	// Mock necessary bank calls
 	bookkepingBankMock.EXPECT().SendCoinsFromAccountToModule(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).AnyTimes().Return(nil)
 	bookkepingBankMock.EXPECT().SendCoinsFromModuleToAccount(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).AnyTimes().Return(nil)
+	bookkepingBankMock.EXPECT().SendCoinsFromModuleToModule(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).AnyTimes().Return(nil)
 	bookkepingBankMock.EXPECT().BurnCoins(gomock.Any(), gomock.Any(), gomock.Any(), gomock.Any()).AnyTimes().Return(nil)
```
Comment (IgnatovFedor) [inline inference-chain/x/inference/keeper/collateral_integration_test.go]: I think this line should be removed, since after this PR BurnCoins is never called from collateral module.

File: inference-chain/x/collateral/types/expected_keepers.go [hunk 2]
```diff
@@ -21,6 +21,7 @@ type BankKeeper interface {
 // BankEscrowKeeper Methods imported from bank should be defined here
 type BookkeepingBankKeeper interface {
 	SendCoinsFromModuleToAccount(ctx context.Context, senderModule string, recipientAddr sdk.AccAddress, amt sdk.Coins, memo string) error
+	SendCoinsFromModuleToModule(ctx context.Context, senderModule, recipientModule string, amt sdk.Coins, memo string) error
 	SendCoinsFromAccountToModule(ctx context.Context, senderAddr sdk.AccAddress, recipientModule string, amt sdk.Coins, memo string) error
 	BurnCoins(ctx context.Context, moduleName string, amt sdk.Coins, memo string) error
```
Comment (IgnatovFedor) [inline inference-chain/x/collateral/types/expected_keepers.go]: Should be removed, since BurnCoins is no longer called anywhere in the collateral keeper after this PR.

**Review by slandymani — APPROVED** [review]

File: inference-chain/x/collateral/types/expected_keepers.go [hunk 3]
```diff
@@ -21,8 +21,8 @@ type BankKeeper interface {
 // BankEscrowKeeper Methods imported from bank should be defined here
 type BookkeepingBankKeeper interface {
 	SendCoinsFromModuleToAccount(ctx context.Context, senderModule string, recipientAddr sdk.AccAddress, amt sdk.Coins, memo string) error
+	SendCoinsFromModuleToModule(ctx context.Context, senderModule, recipientModule string, amt sdk.Coins, memo string) error
 	SendCoinsFromAccountToModule(ctx context.Context, senderAddr sdk.AccAddress, recipientModule string, amt sdk.Coins, memo string) error
-	BurnCoins(ctx context.Context, moduleName string, amt sdk.Coins, memo string) error
```
Comment (qdanik) [inline inference-chain/x/collateral/types/expected_keepers.go:25]: @slandymani 
should we clear `BurnCoins` in [expected_keepers_mocks.go](https://github.com/gonka-ai/gonka/blob/main/inference-chain/testutil/keeper/expected_keepers_mocks.go#L1019C1-L1030C2)?

Comment (x0152) [reply inference-chain/x/collateral/types/expected_keepers.go:25]: I think we shouldn't. That file is autogenerated, so manual changes will be overwritten on regeneration

**Review by patimen — APPROVED** [review]
