### PR TITLE
MLNode: fixes, model management, gpu info

### LINKED ISSUE #316: [P0] Missing validation and inference request threshold adjustment / stattest
Proposal: https://github.com/gonka-ai/gonka/tree/gm/fraud-detection/proposals/fraud-detection-v2

### PR DESCRIPTION
**Pull request by gmorgachev**
# MLNode Management & vLLM Stability Improvements

### 1. Model Management API

New REST endpoints for HuggingFace model lifecycle management:

**Endpoints:**
- `POST /api/v1/models/status` - Check cache status with integrity verification
- `POST /api/v1/models/download` - Start async download (max 3 concurrent)
- `DELETE /api/v1/models` - Cancel download or delete from cache
- `GET /api/v1/models/list` - Enumerate cached models
- `GET /api/v1/models/space` - Cache size and available disk space

**Key features:**
- Background async downloads using `asyncio` tasks in subprocesses
- Post-download integrity verification: validates checksums for all files using `hf_hub_download(..., local_files_only=True)`
- Status tracking: `DOWNLOADED`, `DOWNLOADING`, `NOT_FOUND`, `PARTIAL`
- Resume support for interrupted downloads

### 2. GPU Monitoring API

Read-only GPU monitoring using `pynvml` (official NVIDIA bindings):

**Endpoints:**
- `GET /api/v1/gpu/devices` - Device list with metrics (memory, utilization, temperature, availability)
- `GET /api/v1/gpu/driver` - Driver versions (driver, CUDA, NVML)

**Features:**
- Direct NVIDIA driver API access (no subprocess parsing)
- Per-device error reporting with `is_available` flag

### 3. vLLM Deployment Stability Fixes

**Process termination improvements:**
- Uses `psutil` to terminate vLLM process tree (parent + all children recursively)
- SIGTERM with 20s timeout, then SIGKILL for remaining processes
- GPU memory cleanup via `torch.cuda.empty_cache()` after process termination

**Graceful shutdown for active inference requests:**
- AsyncIO task cancellation for in-flight streaming requests
- `shutdown_event` signals rejection of new requests immediately
- Active streaming tasks cancelled via `task.cancel()`, interrupts blocking I/O
- Cleanup in generator's `finally` block ensures backend release in all scenarios
- Timeout-protected cancellation (30s), essential cleanup guaranteed in `finally` block

**Async deployment API:**
- `POST /inference/up/async` - Non-blocking startup with background initialization
- `GET /inference/up/status` - Check startup progress
- Returns immediately while vLLM initializes in background

**Bug fixes:**
- Fixed flashinfer broken cache issue (cache directory initialization)

### MLNodeBackgroundManager

Isolated background component (single goroutine, 30min ticker) with two functions:

**1. Model pre-download for next epoch:**
- Checks if MLNodes have models for upcoming epochs during safe window only
- Window: `Inference` phase, block >= `SetNewValidators + 30`, block <= `InferenceValidationCutoff - 200`
- Triggers `DownloadModel()` for `NOT_FOUND` or `PARTIAL` models
- Non-blocking: continues on errors, gracefully handles `ErrAPINotImplemented`

**2. GPU hardware detection:**
- Fetches GPU info from `/api/v1/gpu/devices`, transforms to `Hardware` entries
- Format: `"NVIDIA RTX 3090 | 24GB"` (groups by type, counts identical GPUs)
- Dual update: config (persistence) + broker state via `UpdateNodeHardwareCommand` (immediate effect)
- Broker propagates to chain on next `syncNodes()`

**Architecture:**
- Gracefully handles MLNodes without new endpoints (logs "endpoint not available", continues)
- Never blocks or fails on missing endpoint support

### CODE REVIEW

File: decentralized-api/broker/node_worker_commands.go [hunk 1]
```diff
@@ -212,12 +212,37 @@ func (c InferenceUpNodeCommand) Execute(ctx context.Context, worker *NodeWorker)
...
 
-	// Start inference
 	if len(worker.node.State.EpochModels) == 0 {
-		result.Succeeded = false
-		result.Error = "No epoch models available for this node"
-		result.FinalStatus = types.HardwareNodeStatus_FAILED
-		logging.Error(result.Error, types.Nodes, "node_id", worker.nodeId)
+		govModels, err := worker.broker.chainBridge.GetGovernanceModels()
+		if err != nil {
+			result.Succeeded = false
```
Comment (0xBECEDA) [inline decentralized-api/broker/node_worker_commands.go:218]: Let's create method, which would change all this 3 fields. As I understand, they all have to be actualized always, or?

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 2]
```diff
@@ -0,0 +1,333 @@
...
+	"errors"
+	"fmt"
+	"sort"
+	"time"
+
+	"github.com/productscience/inference/x/inference/types"
+)
+
+// ConfigManagerInterface defines the minimal interface needed from ConfigManager
+type ConfigManagerInterface interface {
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go]: Maybe NodesConfigManager? Because it is needed for nodes only

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 3]
```diff
@@ -0,0 +1,333 @@
...
+	if epochState.CurrentPhase != types.InferencePhase {
+		return false
+	}
+
+	currentBlock := epochState.CurrentBlock.Height
+	setNewValidators := epochState.LatestEpoch.SetNewValidators()
+	inferenceValidationCutoff := epochState.LatestEpoch.InferenceValidationCutoff()
+
+	// Window: [SetNewValidators + 30, InferenceValidationCutoff - 200]
+	windowStart := setNewValidators + 30
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go:115]: Why such numbers?

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 4]
```diff
@@ -0,0 +1,333 @@
...
+	for modelId := range node.Models {
+		model := mlnodeclient.Model{
+			HfRepo:   modelId,
+			HfCommit: nil, // nil = latest
+		}
+
+		statusResp, err := client.CheckModelStatus(ctx, model)
+		if err != nil {
+			var apiNotImplemented *mlnodeclient.ErrAPINotImplemented
+			if errors.As(err, &apiNotImplemented) {
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go:146]: Minor, but more "golang" way for it would be
`errors.As(err, mlnodeclient.ErrAPINotImplemented)`

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 5]
```diff
@@ -0,0 +1,333 @@
...
+		switch statusResp.Status {
+		case mlnodeclient.ModelStatusNotFound, mlnodeclient.ModelStatusPartial:
+			logging.Info("Pre-downloading model",
+				types.System,
+				"model", modelId,
+				"node_id", node.Id)
+
+			_, err := client.DownloadModel(ctx, model)
+			if err != nil {
+				logging.Warn("Failed to start model download",
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go:173]: Why warn if it is error?

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 6]
```diff
@@ -0,0 +1,333 @@
...
+
+func formatURLWithVersion(host string, port int, version string, segment string) string {
+	return fmt.Sprintf("http://%s:%d/%s%s", host, port, version, segment)
+}
+
+// checkAndUpdateGPUs fetches GPU info from all nodes and updates hardware
+func (m *MLNodeBackgroundManager) checkAndUpdateGPUs(ctx context.Context) {
+	nodes := m.configManager.GetNodes()
+	updatedNodes := make([]apiconfig.InferenceNodeConfig, len(nodes))
+	copy(updatedNodes, nodes)
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go]: I am not sure about copy, how it deals with "pointer types" like maps. If it doesn't create a new object in that case, we might have some same objects and if we modify some of them, it would be crazy hard to debug it.

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 7]
```diff
@@ -0,0 +1,333 @@
...
+
+	for i := range updatedNodes {
+		node := &updatedNodes[i]
+
+		hardware, err := m.fetchNodeGPUHardware(ctx, node)
+		if err != nil {
+			var apiNotImplemented *mlnodeclient.ErrAPINotImplemented
+			if errors.As(err, &apiNotImplemented) {
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go:248]: Minor, but same stile thing

File: decentralized-api/internal/modelmanager/mlnode_background_manager.go [hunk 8]
```diff
@@ -0,0 +1,333 @@
...
+
+		if len(hardware) == 0 {
+			continue
+		}
+
+		// Update config
+		node.Hardware = hardware
+
+		// Update broker (for immediate chain sync)
+		responseChan := make(chan error, 1)
```
Comment (0xBECEDA) [inline decentralized-api/internal/modelmanager/mlnode_background_manager.go:264]: channel mus be closed after we return from function, otherwise it is memory leak

**Review by 0xBECEDA — APPROVED** [review]
