### PR TITLE
fix: minor bugs

### LINKED ISSUE #562: GetEpochModel in validation should use inference epoch
Follow-up to #553. Line 68 uses GetEpochModel (current epoch) instead of GetEpochModelForEpoch(ctx, inference.EpochId, inference.Model)

### PR DESCRIPTION
**Pull request by x0152**
There are three commits:
1. Division by zero rare edge case when a single participant runs a single model. The denominator becomes zero - panic and crashes the node
2. HTTP timeout - critical, potential DoS. if remote side accepts connection but never respond, goroutine blocks forever. Possible scenario: collect many connection and will crash node
3. CheckStatusRoutine create timer that triggers only once. After first tick, goroutine blocks forever waiting for a channel that will never respond
4. Validation model lookup uses wrong epoch. Causes incorrect validator rejection for previous epoch inferences (Fixes #562)

### CODE REVIEW

**Comment by x0152** [comment]
@0xMayoor You're right. However, this is not a single isolated issue. I don't see any transactional approach. So for this purpose the best idea make another PR and set all atomicity l fixes there.

I've removeв the 4th commit from this PR to keep it focused on minor bugs

File: decentralized-api/internal/server/public/post_chat_handler.go [hunk 1]
```diff
@@ -397,7 +397,7 @@ func (s *Server) handleTransferRequest(ctx echo.Context, request *ChatRequest) e
 	req.Header.Set(utils.XPromptHashHeader, inferenceRequest.PromptHash)
 	req.Header.Set("Content-Type", request.Request.Header.Get("Content-Type"))
 
-	resp, err := NewNoRedirectClient().Do(req)
```
Comment (DimaOrekhovPS) [inline decentralized-api/internal/server/public/post_chat_handler.go:400]: Please take a look at how `NewNoRedirectClient` is constructed and make sure the new `s.httpClient` also doesn't allow redirects

File: inference-chain/x/inference/calculations/should_validate.go [hunk 2]
```diff
@@ -20,6 +20,9 @@ func ShouldValidate(
 	validationParams *types.ValidationParams,
 	debug bool,
 ) (bool, string) {
+	if totalPower <= executorPower {
+		return false, "ShouldValidate:false"
```
Comment (DimaOrekhovPS) [inline inference-chain/x/inference/calculations/should_validate.go]: Let's log an error here, it's an abnormal situation

File: inference-chain/x/inference/keeper/epoch_models.go [hunk 3]
```diff
@@ -8,14 +8,23 @@ import (
...
+	effectiveEpochIndex, found := k.GetEffectiveEpochIndex(ctx)
+	if !found {
+		return nil, types.ErrEffectiveEpochNotFound
+	}
+	return k.GetEpochModelForEpoch(ctx, effectiveEpochIndex, modelId)
+}
+
+// GetEpochModelForEpoch retrieves the model snapshot for a given model ID from a specific epoch.
+func (k Keeper) GetEpochModelForEpoch(ctx context.Context, epochId uint64, modelId string) (*types.Model, error) {
+	epochGroup, err := k.GetEpochGroup(ctx, epochId, "")
```
Comment (DimaOrekhovPS) [inline inference-chain/x/inference/keeper/epoch_models.go]: We can just pass in `modelId` here instead of the empty string and get the `modelSubGroup` right away

**Review by DimaOrekhovPS — CHANGES_REQUESTED** [review]
Please fix the http client and optimize getting the epoch group

File: decentralized-api/internal/server/public/post_chat_handler.go (hunk 1 above)
Comment (x0152) [reply decentralized-api/internal/server/public/post_chat_handler.go:400]: Thanks! NoRedirectClient used

File: inference-chain/x/inference/calculations/should_validate.go (hunk 2 above)
Comment (x0152) [reply inference-chain/x/inference/calculations/should_validate.go]: Logged as error

File: inference-chain/x/inference/keeper/epoch_models.go (hunk 3 above)
Comment (x0152) [reply inference-chain/x/inference/keeper/epoch_models.go]: Fixed. Direct modelId lookup. Thanks

**Review by DimaOrekhovPS — APPROVED** [review]
