### PR TITLE
[P0] Support multipart openai requests

### LINKED ISSUE #985: [P0] Bug: unsupported OpenAI type input for the inference requests
decentralized-api rejects valid Cursor/OpenAI chat requests where messages[].content is an array of text parts instead of a plain string. The request fails during request parsing on TA/executor because Message.Content is typed as string, producing 500 {"error":"json: cannot unmarshal array into Go struct field ... content of type string"} even though the payload is valid modern chat-completions format.

### PR DESCRIPTION
**Pull request by DimaOrekhovPS**

### CODE REVIEW

File: decentralized-api/internal/server/public/entities.go [hunk 1]
```diff
@@ -31,7 +35,80 @@ type OpenAiRequest struct {
...
+}
+
+type MessageContent struct {
+	Text  *string
+	Parts []ContentPart
+}
+
+type ContentPart struct {
+	Type string `json:"type"`
+	Text string `json:"text,omitempty"`
```
Comment (akup) [inline decentralized-api/internal/server/public/entities.go]: Maybe add here "image_url" field?

Comment (DimaOrekhovPS) [reply decentralized-api/internal/server/public/entities.go]: Decided to go with a more general approach to preserve any unserialized fields

File: decentralized-api/internal/server/public/post_chat_handler.go [hunk 2]
```diff
@@ -294,9 +294,10 @@ func (s *Server) handleTransferRequest(ctx echo.Context, request *ChatRequest) e
...
-	promptText := ""
-	for _, message := range request.OpenAiRequest.Messages {
-		promptText += message.Content + "\n"
+	promptText, ignoredParts := FlattenMessagesText(request.OpenAiRequest.Messages)
+	if ignoredParts > 0 {
+		logging.Info("Ignored non-text prompt parts while estimating prompt size", types.Inferences,
+			"ignored_parts", ignoredParts, "model", request.OpenAiRequest.Model)
 	}
 
 	promptTokenCount, err := s.getPromptTokenEstimation(promptText, request.OpenAiRequest.Model)
```
[the remark this answers is not in the document]
Comment (DimaOrekhovPS) [reply decentralized-api/internal/server/public/post_chat_handler.go:303]: We will fail before transaction creation anyway, not worth refactoring

**Comment by x0152** [comment]
Why do we pass through image_url and other non-text parts if the current model only supports text? Shouldn't we return 400 for them for now, or align allowed types to model capabilities?

**Comment by DimaOrekhovPS** [comment]
> Why do we pass through image_url and other non-text parts if the current model only supports text? Shouldn't we return 400 for them for now, or align allowed types to model capabilities?

I think it’s better to keep the API flexible for now so we don’t create unnecessary obstacles, for example around tool-calling workflows. It also doesn’t seem like a security issue to keep the API validation lenient here.

**Review by 0xgonka — APPROVED** [review]
