### PR TITLE
fix: avoid rewriting config on every startup

### LINKED ISSUE #466: Stop rewriting static config at each app start

### PR DESCRIPTION
**Pull request by x0152**
fixes #466

### CODE REVIEW

File: decentralized-api/apiconfig/config_manager.go [hunk 1]
```diff
@@ -70,17 +70,19 @@ func LoadConfigManagerWithPaths(configPath, sqlitePath, nodeConfigPath string) (
...
 		log.Printf("Error migrating dynamic data to DB: %+v", err)
 		return nil, err
 	}
 
-	if err = manager.Write(); err != nil {
-		log.Printf("Error writing config: %+v", err)
-		return nil, err
+	if migrated {
+		if err = manager.Write(); err != nil {
+			log.Printf("Error writing config: %+v", err)
```
Comment (patimen) [inline decentralized-api/apiconfig/config_manager.go:81]: Let's use our standard logging (logging.Info) instead of a println.

Comment (x0152) [reply decentralized-api/apiconfig/config_manager.go:81]: valid point, thanks - fixed it
