### PR TITLE
fix: guard nil participants in executor selection

### LINKED ISSUE #499: Chat Completions aren't working
```
base_url: http://192.241.240.19:8000/v1
Request signing is enabled through a custom HTTP client implementation.
Using Gonka address: gonka1twg5lhad6sc86yjqspanmp94md2dx0fhfppxus
INFO:httpx:HTTP Request: POST http://192.241.240.19:8000/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 0.400175 seconds
INFO:httpx:HTTP Request: POST http://192.241.240.19:8000/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
INFO:openai._base_client:Retrying request to /chat/completions in 0.879420 seconds
INFO:httpx:HTTP Request: POST http://192.241.240.19:8000/v1/chat/completions "HTTP/1.1 500 Internal Server Error"
Traceback (most recent call last):
  File "/Users/bob/git/gonka/script.py", line 9, in <module>
    response = client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/git/gonka/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 286, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/git/gonka/.venv/lib/python3.12/site-packages/openai/resources/chat/completions/completions.py", line 1192, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/bob/git/gonka/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1259, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/git/gonka/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1047, in request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'error': 'rpc error: code = Unknown desc = runtime error: invalid memory address or nil pointer dereference: panic'}
```

script

```
import os
from gonka_openai import GonkaOpenAI

client = GonkaOpenAI(
    gonka_private_key=os.environ.get('GONKA_PRIVATE_KEY'),
    source_url="http://node3.gonka.ai:8000",
)

response = client.chat.completions.create(
    model="Qwen/Qwen3-235B-A22B-Instruct-2507-FP8",
    messages=[
        { "role": "user", "content": "Write a one-sentence bedtime story about a unicorn" }
    ]
)

print(response.choices[0].message.content)
```

### PR DESCRIPTION
**Pull request by x0152**
guard nil participants (maybe fixes #499)

### CODE REVIEW

File: inference-chain/x/inference/epochgroup/random.go [hunk 1]
```diff
@@ -87,9 +89,26 @@ func computeCumulativeArray(participants []*group.GroupMember) []int64 {
...
+		return 0
+	}
 	weight, err := strconv.Atoi(participant.Member.Weight)
 	if err != nil {
 		return 0
 	}
 	return int64(weight)
 }
+
+func sanitizeMembers(members []*group.GroupMember) []*group.GroupMember {
```
Comment (patimen) [inline inference-chain/x/inference/epochgroup/random.go:101]: We might want to filter in place instead of creating a new slice? But unlikely to be an issue.

File: inference-chain/x/inference/epochgroup/random.go [hunk 2]
```diff
@@ -43,11 +43,13 @@ func (eg *EpochGroup) GetRandomMember(
 	if err != nil {
 		return nil, status.Error(codes.Internal, err.Error())
 	}
+	activeParticipants = sanitizeMembers(activeParticipants)
 	if len(activeParticipants) == 0 {
 		return nil, status.Error(codes.Internal, "Active participants found, but length is 0")
 	}
 
 	filteredParticipants := filterFn(activeParticipants)
+	filteredParticipants = sanitizeMembers(filteredParticipants)
```
Comment (patimen) [inline inference-chain/x/inference/epochgroup/random.go]: Why do we need to sanitize again?

Comment (x0152) [reply inference-chain/x/inference/epochgroup/random.go]: Hi!
My thinking was that filterFn can be any filter and GetRandomMember is reusable, so the extra sanitizeMembers is a cheap safety net if future filter doesn’t guard against nil

Comment (x0152) [reply inference-chain/x/inference/epochgroup/random.go]: But now I think it looks a bit strange, since it’s unlikely anyone will add logic like that inside the filter lambda so I’ll remove it. 
Thanks

File: inference-chain/x/inference/epochgroup/random.go (hunk 1 above)
Comment (x0152) [reply inference-chain/x/inference/epochgroup/random.go:101]: Just in case activeParticipants is being used by another goroutine at the same time
I think copying is safer and cleaner, and the overhead here is minimal
