### PR TITLE
IBC Trade Support

### LINKED ISSUE #615: IBC support, IBC pool

### LINKED ISSUE #756: Certik, Ethereum Bridge, Preliminary Report (v1), Severity: Medium [Priority 4]
- [ ] [GEB-04 | Incorrect Signing Threshold in `checkThresholdAndAggregate()`](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-04)
- [ ] [GEB-05 | Native Denom Auto-Detection Can Be Misconfigured in `community-sale` Contract](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-05)
- [ ] [GEB-13 | Aggregation of BLS Partial Signature Does Not Eliminate Duplicates](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-13)
- [ ] [GEB-14 | User-Controlled RequestId Allows Front-Run Poisoning of Threshold Signing](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-14)
- [ ] [GEB-15 | Cross-Chain Address Collision](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-15)
- [ ] [GEB-16 | Bridge BLS Signatures Are Not Bound to Destination Contract](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-16)
- [ ] [GEB-17 | Dealer Validation Majority Is Too Weak for Safe Key Recovery](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-17)
- [ ] [GEB-35 | Secret Shares Not Using Consensus `ValidDealers`](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-35)
- [ ] [GEB-36 | Authority Mismatch In `MigrateAllWrappedTokenContracts()`](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-36)
- [ ] [GEB-55 | BLS Genesis Export/Import Drops In-flight DKG and Signing state](https://skyharbor.certik.com/shared-report/c4dcdbdc-c10d-40c7-a8ff-894e13a1cb17?findingIndex=GEB-55)

### LINKED ISSUE #757: [P1] Certik, Ethereum Bridge, Preliminary Report (v1), Severity: Minor [Priority 5]
- [x] GEB-06 | Known Security Issue in Upstream Dependencies - https://github.com/gonka-ai/gonka/pull/675
- [x] GEB-07 | Weak Address Validation in `withdraw()` in `wrapped-token` Contract - https://github.com/gonka-ai/gonka/pull/814
- [x] GEB-08 | `ADMIN` Role Cannot Not Be Updated https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-09 | Migration From cw20‑base Leaves Required Wrapped‑Token State Uninitialized https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-10 | Migration of `community‑sale` Lacks Compatibility Checks and State Validation - https://github.com/gonka-ai/gonka/pull/814
- [x] GEB-18 | Slot Donation Picks Under-Allocated Donor, Enabling Sybil Weight Inflation - #822 
- [x] GEB-19 | Secret Shares Logged in `logging.Debug` - #822 
- [x] GEB-20 | Decoding Returns Zero If Fails https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-21 | Ineffective Polynomial Degree Check in `evaluatePolynomial()` https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-22 | Unchecked `amountToBytes32()` Panic on Oversized Amounts https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-23 | Missing Validation of `MsgRequestThresholdSignature.ValidateBasic()` for `chain_id`/`request_id` and Data Chunk Sizes - #822 
- [x] GEB-24 | Insufficient Validation for Dealer Part Submissions in `MsgSubmitDealerPart.ValidateBasic()` - #822 
- [x] GEB-25 | Missing Validation in Group Key Validation Signatures in `MsgSubmitGroupKeyValidationSignature.ValidateBasic()` - #822 
- [x] GEB-26 | Missing Validation in Partial Signature Submissions in `MsgSubmitPartialSignature.ValidateBasic()` - #822 
- [x] GEB-27 | Unbounded `DealerValidity` in Verification Vector Submissions of `MsgSubmitVerificationVector.ValidateBasic()` - #822 
- [x] GEB-37 | DKG Process Can Be Stuck Due to Internal Errors https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-38 | Inconsistent Comparison of Deadline Block https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-39 | Missing Validation of `msg.Amount` Being Positive in `MsgRequestBridgeWithdrawal` - https://github.com/gonka-ai/gonka/pull/814
- [x] GEB-40 | Broken Cleanup Logic https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-42 | Unhandled Error of `EmitTypedEvent()` https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-43 | Valid Dealers Can Be Less Than Threshold https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-47 | Hard-coded threshold for BLS signature https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-48 | Missing Signed Status in `parseEpochDataFromJSON()` https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-49 | Missing Check of Withdrawal and Mint Amount https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-56 | Missing Validation of Epoch Id in `RequestThresholdSignature()` https://github.com/gonka-ai/gonka/pull/949
- [x] GEB-57 | Slot Range Silently Clamped Instead of Failing https://github.com/gonka-ai/gonka/pull/949

### PR DESCRIPTION
**Pull request by GLiberman**
# Proposal: Enable IBC Token Trading via Governance

## Overview
This proposal enables the trading of **Native and IBC Tokens** in the Gonka Liquidity Pool and Community Sale contract by introducing a dedicated governance approval workflow. This is specifically designed to support stablecoin representations in the Cosmos ecosystem (such as `USDC` or `USDT`) as alternative to CW20 bridge wrapper.

## Core Design Principles
1.  **Strict Separation of Logic**: IBC-specific logic lives in separate files (`ibc_wrapped_token.go`) and uses separate messages (`MsgApproveIbcTokenForTrading`).
2.  **Unified Available List**: While logic is separate, approvals are stored in the *same* underlying map (`LiquidityPoolApprovedTokensMap`). This ensures the existing `ApprovedTokensForTrade` query automatically returns both CW20 and IBC tokens to UIs.
3.  **Distinct Validation Paths**: The Liquidity Pool Contract will use a *new* specific query (`ValidateIbcTokenForTrade`) for IBC tokens, acknowledging that their metadata lives in the Bank module, not the Bridge store.

#### A. New Protocol Definitions
*   **Message**: `MsgApproveIbcTokenForTrading`
    *   **Usage**: Governance submits this to valid an IBC denom.
    *   **Convention**: `ChainId="ibc"`, `ContractAddress="ibc/HASH"` (or native denom).
*   **Query**: `ValidateIbcTokenForTrade`
    *   **Usage**: Called by the Liquidity Pool contract to verify an IBC token before adding it.

#### B. Implementation (`x/inference/keeper`)
We introduce new files to mirror the existing bridge functionality but adapted for IBC:
*   `ibc_wrapped_token.go`: Handles storage of approvals (allowing `/` in regex).
*   `query_ibc_token.go`: Handles validation logic.
    *   **Metadata Check**: Verifies `BankKeeper.GetDenomMetaData(ctx, denom)` exists (ensuring UI has decimals/symbol).
    *   **Allowlist Check**: Verifies the token is in `LiquidityPoolApprovedTokensMap`.
*   `msg_server_register_ibc_token_metadata.go`: Handles dual-writing of metadata.
    *   **Internal Map**: Stores metadata in `WrappedTokenMetadataMap` for bridge-specific logic.
    *   **Bank Module integration**: Calls `BankKeeper.SetDenomMetaData` to ensure the IBC token decimals and symbol are visible via standard Cosmos bank queries and explorers.

#### C. Contract Migration Integration (`app/upgrades/v0_2_11`)
*   **Upgrade Handler**: Added CosmWasm contract migration steps directly into the consensus upgrade.
*   **Execution**: Parses the governance `Plan.Info` field for a JSON string containing `community_sale_address` and `new_code_id`. Utilizing `wasmkeeper`, it safely executes the contract migration, automatically triggering the update payload to enable new configuration `allow_all_trade_tokens`.

#### A. Dynamic Token Validation
*   **Method**: `validate_wrapped_token_for_trade` and `validate_ibc_token_for_trade`
*   **Logic Change**: The concept of a maintained `PAYMENT_TOKENS` map has been removed. The contract will now dynamically detect the token type and validate it against the chain module at the moment of purchase:
    *   **CW20**: Calls legacy `ValidateWrappedTokenForTrade`.
    *   **IBC/Native**: Calls new `ValidateIbcTokenForTrade`.
*   **Result**: Validates the token and retrieves necessary decimals directly from the chain API as the source of truth, removing duplicate state handling in the contract.

#### B. Native Token Purchase & Fund Accumulation
*   **Target**: `ExecuteMsg::PurchaseWithNative` and CW20 `Receive`
*   **Logic**:
    *   Accepts `info.funds` (strictly 1 coin).
    *   Dynamically validates the token and normalizes its USD value using the decimals sourced from the chain.
    *   **Accumulation**: Instead of forwarding received tokens to the `admin` account immediately, both CW20 and Native/IBC tokens safely accumulate in the contract's balance. This design change was necessary because the governance (admin) account does not have the ability to sign and execute CW20 smart contract transfer messages. If forwarded directly to governance, CW20 tokens would become permanently stuck. Administrators can withdraw funds using dedicated withdrawal functions.

#### C. Direct Token Querying
*   **Target**: `QueryMsg::TestApprovedTokens` (superseding local state queries)
*   **Logic**:
    *   Directly queries the Chain API `ApprovedTokensForTrade` (which automatically returns *both* lists due to the shared state in `LiquidityPoolApprovedTokensMap`).
    *   Returns the unmerged raw list directly to the UI for consumption alongside dynamic rate querying.

#### A. IBC Payment Support
*   **Method**: `ExecuteMsg::PurchaseWithNative`
*   **Logic**: Added support for purchasing GNK using native IBC tokens (e.g., Nobel USDC). The contract validates the IBC denom against the governance-maintained allowlist on the chain.

#### B. Dynamic Multi-Token Support (`allow_all_trade_tokens`)
*   **Method**: `ExecuteMsg::UpdateAllowAllTradeTokens` & `Config` structural changes.
*   **Logic**: Introduced an `allow_all_trade_tokens` configuration boolean. When enabled, the contract bypasses checks for a *single* strictly defined `accepted_ibc_denom` or `accepted_eth_contract`. Instead, it mirrors the `liquidity-pool` behavior by independently validating *any* received token dynamically against the on-chain governance allowlist (via `ValidateWrappedTokenForTrade` and `ValidateIbcTokenForTrade` queries).

#### C. Migration Support
*   **Migration Path**: Implemented a comprehensive `migrate` entry point that allows existing contract instances (like the one funded in Proposal 14) to be safely upgraded to this new version.
*   **Config Backwards-Compatibility**: If no V3 configuration updates are passed during migration, the contract perfectly retains the pre-migration restrictions (falling back to requiring the explicitly defined single token configurations) preserving the expected behavior of any active legacy contracts.

---

## Bridge Audit Fixes Included in This PR

The following security findings from Certik bridge audit have been resolved as part of this change set:

| ID | Severity | Title | Fixed In |
|----|----------|-------|----------|
| GEB-05 | Medium | Native Denom Auto-Detection Can Be Misconfigured in `community-sale` Contract | `community-sale/src/contract.rs` |
| GEB-07 | Minor | Weak Address Validation in `withdraw()` in `wrapped-token` Contract | `contracts/wrapped-token/src/contract.rs` |
| GEB-10 | Minor | Migration of `community‑sale` Lacks Compatibility Checks and State Validation | `community-sale/src/contract.rs` |
| GEB-11 | Info | `InstantiateMsg.marketing` Is Ignored | `contracts/wrapped-token/src/contract.rs` |
| GEB-15 | Medium | Cross-Chain Address Collision in `IsBridgeContractAddress()` | `keeper/bridge_native.go` |
| GEB-36 | Medium | Authority Mismatch In `MigrateAllWrappedTokenContracts()` | `keeper/bridge_wrapped_token.go` |
| GEB-39 | Minor | Missing Validation of `msg.Amount` Being Positive in `MsgRequestBridgeWithdrawal` | `types/message_request_bridge_withdrawal.go` |

### Summary of Fixes

- **GEB-05**: Native denom is now passed explicitly as an instantiation parameter instead of being auto-detected from bank supply, preventing manipulation attacks.
- **GEB-07**: `withdraw()` now validates that `destination_address` conforms to the Ethereum address format (0x + 40 hex chars) to prevent permanent fund loss from invalid destinations.
- **GEB-10**: The community-sale migrate() entry point only reads the previous contract version and writes a new version. It does not validate the previous contract name/version nor confirm that required state (CONFIG) exists. A mistaken migration from an unrelated contract or a corrupted state will still “succeed,” but subsequent calls that load CONFIG will error, leaving the contract unusable.
- **GEB-11**: Removed the unused `marketing` field from `InstantiateMsg` — marketing info is hardcoded and governed on-chain via the governance module.
- **GEB-15**: `IsBridgeContractAddress()` now takes `chainId` as a parameter and checks the exact `(chainId, address)` pair, preventing cross-chain address collisions with CREATE2/deterministic deployments.
- **GEB-36**: `MigrateAllWrappedTokenContracts()` now correctly uses the governance address (matching how contracts were instantiated) instead of the inference module address, resolving the authorization mismatch that caused DoS.
- **GEB-39**: `MsgRequestBridgeWithdrawal.ValidateBasic()` now parses and validates that `Amount` is a positive integer using `math.NewIntFromString`, rejecting zero, negative, and non-numeric values.

### CODE REVIEW

File: inference-chain/contracts/wrapped-token/src/contract.rs
Comment (x0152) [inline inference-chain/contracts/wrapped-token/src/contract.rs:206]: Hi
Shouldn't this be dest_trimmed here?

File: inference-chain/x/inference/keeper/query_ibc_token.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+	var chainId string
+	isApproved := false
+
+	iter, err := k.LiquidityPoolApprovedTokensMap.Iterate(sdkCtx, nil)
+	if err != nil {
+		return false, banktypes.Metadata{}, fmt.Errorf("failed to iterate approved tokens: %w", err)
+	}
+	defer iter.Close()
+
+	for ; iter.Valid(); iter.Next() {
```
Comment (x0152) [inline inference-chain/x/inference/keeper/query_ibc_token.go:35]: Could full scan iteration become expensive over time?

File: inference-chain/app/upgrades/v0_2_11/upgrades.go [hunk 2]
```diff
@@ -45,11 +54,66 @@ func CreateUpgradeHandler(
 			return toVM, err
 		}
 
+		// Execute Dynamic Contract Migration from Plan.Info
+		if err := executeContractMigration(ctx, k, plan.Info); err != nil {
```
Comment (patimen) [inline inference-chain/app/upgrades/v0_2_11/upgrades.go:55]: This should be above the RunMigrations portion.

File: inference-chain/app/upgrades/v0_2_11/upgrades.go [hunk 3]
```diff
@@ -45,11 +54,66 @@ func CreateUpgradeHandler(
...
+func executeContractMigration(ctx context.Context, k keeper.Keeper, infoJSON string) error {
+	if infoJSON == "" {
+		k.LogInfo("no migration data found in Plan.Info, skipping contract migration", types.Upgrades)
+		return nil
+	}
+
+	var data MigrationData
+	if err := json.Unmarshal([]byte(infoJSON), &data); err != nil {
+		k.LogError("failed to unmarshal Plan.Info", types.Upgrades, "info", infoJSON, "error", err)
+		return err
```
Comment (patimen) [inline inference-chain/app/upgrades/v0_2_11/upgrades.go]: I don't think we should halt the chain if there is an issue with the plan.Info JSON... that seems pretty extreme. Maybe log an error and continue?

**Comment by akup** [comment]
I didn't found logical errors.

But it is unrelated to this PR, but bridge related further optimization needed.
I think messages for the bridge inbound/outbound should be batched, so we get all (or N) the transactions for the block in one message. It especially important for inbound transactions, that all validators should vote for, so one tx in Etherium will emit ActiveParticipants number of txs to create wrapped token at gonka

File: inference-chain/x/inference/keeper/ibc_wrapped_token.go [hunk 4]
```diff
@@ -0,0 +1,134 @@
...
+			"chainId", approvedToken.ChainId,
+			"contractAddress", approvedToken.ContractAddress,
+			"error", err)
+		return fmt.Errorf("invalid IBC trade approved token data: %w", err)
+	}
+
+	// Use lowercase key for consistent collection lookups, but preserve original casing
+	// in the stored struct so queries return canonical IBC denom form (e.g. ibc/UPPERCASE_HEX)
+	// matching what x/bank and the IBC module use.
+	lookupKey := strings.ToLower(approvedToken.ContractAddress)
```
Comment (patimen) [inline inference-chain/x/inference/keeper/ibc_wrapped_token.go:27]: But if the cannonical casing is cased, then wouldn't converting it risk collisions? Or are we 100% sure the case is never used as a differentiator?

File: inference-chain/app/upgrades/v0_2_11/upgrades.go [hunk 5]
```diff
@@ -66,6 +81,56 @@ func setEpochParticipantsSets(ctx context.Context, k keeper.Keeper) error {
...
```
Comment (IgnatovFedor) [inline inference-chain/app/upgrades/v0_2_11/upgrades.go]: Empty Plan.Info is handled gracefully (returns nil, skips migration). But non-empty, non-JSON Plan.Info returns an error, which propagates out of the upgrade handler and permanently halts the chain at upgrade height. Shouldn't if err also return nil?

File: inference-chain/x/inference/keeper/bridge_native.go [hunk 6]
```diff
@@ -35,21 +35,21 @@ func (k Keeper) ReleaseFromEscrow(ctx sdk.Context, toAddr sdk.AccAddress, amount
...
 }
 
-// IsBridgeContractAddress checks if the given contract address matches any registered bridge addresses
-func (k Keeper) IsBridgeContractAddress(ctx context.Context, contractAddress string) (bool, string) {
-	// Get all registered bridge contract addresses
-	allBridgeAddresses := k.GetAllBridgeContractAddresses(ctx)
+// IsBridgeContractAddress checks if the given contract address matches any registered bridge addresses for the specific chain
+func (k Keeper) IsBridgeContractAddress(ctx context.Context, chainId, contractAddress string) bool {
+	// Get all registered bridge contract addresses for the specific chain
+	bridgeAddresses := k.GetBridgeContractAddressesByChain(ctx, chainId)
```
Comment (IgnatovFedor) [inline inference-chain/x/inference/keeper/bridge_native.go]: Why not use `HasBridgeContractAddress` directly instead of loading all addresses for the chain and iterating?

File: inference-chain/x/inference/keeper/ibc_wrapped_token_test.go [hunk 7]
```diff
@@ -0,0 +1,237 @@
...
+
+func TestValidateIbcTokenForTrade(t *testing.T) {
+	k, ctx, mocks := keepertest.InferenceKeeperReturningMocks(t)
+	// We need to use the QueryServer interface, but Keeper implements it.
+	// We can call ValidateIbcTokenForTrade directly on k.
+
+	sdk.GetConfig().SetBech32PrefixForAccount("gonka", "gonka")
+
+	denom := "ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2"
+	chainId := "cosmoshub-4"
```
Comment (IgnatovFedor) [inline inference-chain/x/inference/keeper/ibc_wrapped_token_test.go:107]: Should this be "ibc" per the convention in the PR description?

File: inference-chain/x/inference/keeper/query_ibc_token.go (hunk 1 above)
Comment (patimen) [reply inference-chain/x/inference/keeper/query_ibc_token.go:35]: It is highly unlikely we will ever exceed more than a few dozen, and they all have to be approved by governance. We could use an IndexedMap, but it is overkill for the expected usage.

**Review by patimen — APPROVED** [review]
I've done as much as I can on this.
I cannot vouch strongly for the Rust code, other than to assert that I've used about 5 different AI Analysis on it to try and find any issues.
I've fixed a handful of issues where they made sense, but most were advisory.
I am approving also on the assumption that the approved tokens map will never get large.
