### PR TITLE
[P1] fix: remove participant requirement for dev inference

### LINKED ISSUE #744: Don’t require developers to register as Participants to run inference
Currently, the chain requires a Participant record not only to host, but also to send inference requests. There is no real reason for this, since the public key is available in the Account record after the first on-chain transaction signed by that account is executed. That should be sufficient.

- [ ] Remove the requirement to create a Participant record.
- [ ] Fix `/v1/participants/gonka...` to query Participant data, not just the Account (as it does now).
- [ ] Determine how to preserve per-developer statistics in this case.
- [ ] Update the documentation accordingly.

### PR DESCRIPTION
**Pull request by x0152**
Closes #744.

Developers no longer need to register as a Participant to run inference. An account public key from the chain is enough.

Changes:
- Removed Participant lookup in Start / Finish / Invalidate inference
- Fixed /v1/participants/:address — it was returning Account data instead of Participant data
- Added GET /v2/participants/:address and GET /v2/accounts/:address endpoints
- Renamed InferenceParticipant → AccountByAddress, added denom
- /v1 keeps returning Account data for backward compatibility
- Per-developer stats are unaffected — already tracked by account address
- Consumer setup docs updated; gonka-docs follow-up PR after merge

Note: can expose a single /v1 endpoint with both Account + Participant data if needed, but separate v2 endpoints seem cleaner.

### CODE REVIEW

**Comment by patimen** [comment]
I've moved this to 0.2.12 for now, it seems like there are some big questions and it needs careful review.

File: inference-chain/x/inference/calculations/signature_validate.go [hunk 1]
```diff
@@ -28,23 +28,23 @@ type PubKeyGetter interface {
...
 func VerifyKeys(ctx context.Context, components SignatureComponents, sigData SignatureData, pubKeyGetter PubKeyGetter) error {
-	// Check developer signature if developer participant is provided
-	if sigData.Dev != nil && sigData.DevSignature != "" {
-		devKey, err := pubKeyGetter.GetAccountPubKey(ctx, sigData.Dev.Address)
+	// Check developer signature if developer address is provided
+	if sigData.Dev != "" && sigData.DevSignature != "" {
+		devKey, err := pubKeyGetter.GetAccountPubKey(ctx, sigData.Dev)
 		if err != nil {
-			return sdkerrors.Wrap(types.ErrParticipantNotFound, sigData.Dev.Address)
+			return err
```
Comment (slandymani) [inline inference-chain/x/inference/calculations/signature_validate.go]: wrap error with correct account name

File: decentralized-api/internal/server/public/get_participants_handler.go [hunk 2]
```diff
@@ -22,33 +22,108 @@ import (
...
+	case codes.ResourceExhausted:
+		return echo.NewHTTPError(http.StatusTooManyRequests, st.Message())
+	case codes.Unavailable:
+		return echo.NewHTTPError(http.StatusServiceUnavailable, st.Message())
+	default:
+		return echo.NewHTTPError(http.StatusInternalServerError, st.Message())
+	}
+}
+
+func (s *Server) getAccountByAddressV1(c echo.Context) error {
```
Comment (slandymani) [inline decentralized-api/internal/server/public/get_participants_handler.go]: why do we need almost identical getAccountByAddressV1 and getAccountByAddress?

**Review by slandymani — CHANGES_REQUESTED** [review]

File: inference-chain/x/inference/calculations/signature_validate.go (hunk 1 above)
Comment (x0152) [reply inference-chain/x/inference/calculations/signature_validate.go]: valid point, fixed

File: decentralized-api/internal/server/public/get_participants_handler.go (hunk 2 above)
Comment (x0152) [reply decentralized-api/internal/server/public/get_participants_handler.go]: getAccountByAddressV1 is rudiment, deleted

thanks

**Review by slandymani — APPROVED** [review]

**Comment by akup** [comment]
@x0152 please rebase

**Review by Ryanchen911 — APPROVED** [review]
Looks good to me. Approved.

**Review by jacky6block — APPROVED** [review]
LGTM

**Review by 0xgonka — APPROVED** [review]
